### ISSUE TITLE
Not find link

### ISSUE THREAD

**Issue by jitendra3109** [rstats-gsoc/gsoc2016#2]
> Links
   Official Google Summer of Code 2016 page on melange.
Please update link on gsoc 2016 readme.md file.

**Comment by analyticalmonk** [comment]
@jsroyal Have opened a PR to update the link on README.
Here's the link: https://summerofcode.withgoogle.com/archive/2016/organizations/6032418200879104/

**Comment by jitendra3109** [comment]
@analyticalmonk No I just got here and want to know more about R project.
Thanks for giving link.
